'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34003
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("password")>  _
        Public Property password() As String
            Get
                Return CType(Me("password"),String)
            End Get
            Set
                Me("password") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("7")>  _
        Public Property finsh() As Integer
            Get
                Return CType(Me("finsh"),Integer)
            End Get
            Set
                Me("finsh") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Setting() As String
            Get
                Return CType(Me("Setting"),String)
            End Get
            Set
                Me("Setting") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("400000")>  _
        Public Property tryme() As Integer
            Get
                Return CType(Me("tryme"),Integer)
            End Get
            Set
                Me("tryme") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("127.0.0.1")>  _
        Public Property serverhost() As String
            Get
                Return CType(Me("serverhost"),String)
            End Get
            Set
                Me("serverhost") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Ethan")>  _
        Public Property serveruser() As String
            Get
                Return CType(Me("serveruser"),String)
            End Get
            Set
                Me("serveruser") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("password")>  _
        Public Property serverpassword() As String
            Get
                Return CType(Me("serverpassword"),String)
            End Get
            Set
                Me("serverpassword") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property serverdatabase() As String
            Get
                Return CType(Me("serverdatabase"),String)
            End Get
            Set
                Me("serverdatabase") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("AgAAAA**AQAAAA**aAAAAA**ZkDSUg**nY+sHZ2PrBmdj6wVnY+sEZ2PrA2dj6wFk4GhC5eGoQ+dj6x9n"& _ 
            "Y+seQ**En0CAA**AAMAAA**0+c7YnrtrmZWPAC09JeeluJ0Xu5akOAkMGPUsoGdAka05GiXZADHfgDxQ"& _ 
            "SoFBvMMCVv7VGLcSsq2nR/vlAhKHqJ/AxLVbT5o+QLRvWLgHXR4QXWZ3wgEutzecKaNzx1nWUe/KrhBg"& _ 
            "kHJsGWvpRwHLo+oIYUIfO1NYDirsCath8LfpvPuVdMB4uR2Ft7p+/yhUt32CpspRrD4RGDZ2daZty1u+"& _ 
            "6YfT9s5IgLUQY0rpmnnRUhHf7Xg4fvGR0PfviOTlElELXkyOzQT4+bv1NIk7UB3Wg2/tu6BAT2VsIgbj"& _ 
            "dzk/k8OIYT8II5Msss69qOny34NHSAM8GAx+s+un+6CQSd0h4IaiM7tU+u1+2Jv85RABVZ9vOJY37WAy"& _ 
            "Q2KZ0u62+RihFHwYzqnfEz/DnMXqRKnJFzNlVvsKRyISJu9eBBRSX+16g6hH991TfKWjb8r6QoA21Vye"& _ 
            "JWHzmknB/46dsqN4ZWRIDhDlX/nGsBu4zEb9W1hY9tayvsQJxHZow9b49j/6fNshfR6VvjZC175ALFht"& _ 
            "eGc9GppICB4vcR5I2F45Brukmoj2iQohlW50I2B+7VTjs5f/70is78LEDbGNAz2RQUNTROAM1YsEZn72"& _ 
            "O5R9ddFhmOFk8DBTf5HetAbcg5K9tZcMljEjpK6IXCfmzSszw+hHbxI50aZ1/vF6uED3yERcamBVQMHA"& _ 
            "Y3eM2OKX9CI3OWA/VzBfM83EiG2YcftMafYczdWCETq3gV1dZ0b+TpPEc4XLJjSLt2mZIDd")>  _
        Public Property apiToken() As String
            Get
                Return CType(Me("apiToken"),String)
            End Get
            Set
                Me("apiToken") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://api.sandbox.ebay.com/wsapi")>  _
        Public Property ApiServerUrl() As String
            Get
                Return CType(Me("ApiServerUrl"),String)
            End Get
            Set
                Me("ApiServerUrl") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.Inv_Manager.My.MySettings
            Get
                Return Global.Inv_Manager.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
